[package]
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
edition = "2018"
name = "libbrz"
version = "0.1.0"
license = "MPL-2.0/MIT/Apache-2.0"

[dependencies]
common_failures = "*"
failure = "*"
ropey = "*"
default = "*"
slab = "0.4"
once_cell = "0.2.2"
